# Generated by Django 5.2.6 on 2025-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('booked', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
