# Generated by Django 5.2.6 on 2025-09-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booked',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='shop.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='shop.service'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='reserved_until',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
    ]
