# Generated by Django 5.2.6 on 2025-09-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_service_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='capacity',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='shop.timeslot'),
        ),
    ]
